#!/bin/bash
# Script to check production server logs for debugging signup issues

echo "======================================"
echo "Production Server Log Viewer"
echo "======================================"
echo ""
echo "This script helps you check the production server logs."
echo "You'll need SSH access to your production server."
echo ""
echo "Please run these commands on your production server:"
echo ""
echo "1. Check Gunicorn error logs:"
echo "   sudo tail -100 /var/www/visaguardai/logs/gunicorn_error.log"
echo ""
echo "2. Check Gunicorn access logs:"
echo "   sudo tail -100 /var/www/visaguardai/logs/gunicorn_access.log"
echo ""
echo "3. Check system service logs:"
echo "   sudo journalctl -u visaguardai.service -n 200 --no-pager"
echo ""
echo "4. Check nginx error logs:"
echo "   sudo tail -100 /var/log/nginx/error.log"
echo ""
echo "5. Follow logs in real-time (to see errors as you test signup):"
echo "   sudo tail -f /var/www/visaguardai/logs/gunicorn_error.log"
echo ""
echo "======================================"
echo "Common Issues to Look For:"
echo "======================================"
echo "- UserProfile.DoesNotExist errors"
echo "- Signal handler errors"
echo "- Database constraint violations"
echo "- RECAPTCHA verification failures"
echo ""

