# Generated by Django 5.1.3 on 2025-08-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userprofile_facebook_alter_userprofile_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='unversity',
            new_name='university',
        ),
    ]
