# Generated by Django 5.1.3 on 2025-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_unversity_userprofile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
