# Generated by Django 5.1.3 on 2025-08-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_payment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='youtube',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_connected',
            field=models.BooleanField(default=False),
        ),
    ]
