# Generated by Django 5.1.3 on 2025-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_config_delete_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='Price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
