# Generated by Django 5.1.3 on 2025-08-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_config_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
