# Generated by Django 5.1.3 on 2025-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
