# Generated by Django 5.1.3 on 2025-09-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_userprofile_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_login',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
