# Generated by Django 5.1.3 on 2025-09-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_userprofile_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_login',
        ),
    ]
