# Generated by Django 5.1.3 on 2025-09-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_userprofile_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
