# Generated by Django 5.1.3 on 2025-09-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_userprofile_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='Price',
            field=models.IntegerField(blank=True, default=0, help_text='Price in cents (e.g., 1500 = $15.00)', null=True),
        ),
    ]
