# Generated by Django 5.2.5 on 2025-10-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_config_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter_connected',
            new_name='tiktok_connected',
        ),
    ]
