# Generated by Django 5.2.5 on 2025-10-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_twitter_connected_userprofile_tiktok_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter',
        ),
    ]
